services:
  # Web service
  - type: web
    name: job-search-engine
    env: node
    buildCommand: npm install && ./scripts/setup-data.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
